version: '3.8'

services:
  product_dev_service:
    container_name: kk_product
    build:
      context: ./products
      dockerfile: Dockerfile.dev
      target: development
    env_file: ./.env
    restart: unless-stopped
    environment:
      - DB_HOST=product_db
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT    
    ports:
      - 3000:3000
      - 9229:9229
    volumes:  
      - ./products:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    depends_on:
      - product_db

  product_db:
    container_name: kk_product_db
    image: mongo
    env_file: ./.env
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
