FROM node:18 AS development

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build


# FROM node:14 AS builder

# WORKDIR /app

# COPY package*.json ./
# COPY prisma ./prisma/

# RUN npm install

# COPY . .

# EXPOSE 9001

# CMD [ "npm", "run", "dev" ]
